[[constraint]]
  name = "go.uber.org/zap"
  branch = "master"

[[constraint]]
  name =  "github.com/bluele/gcache"
  branch = "master"

[[constraint]]
  name =  "github.com/google/goexpect"
  branch = "master"

[[constraint]]
  name =  "github.com/google/goterm"
  branch = "master"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  branch = "master"

[[constraint]]
  name =  "github.com/jinzhu/copier"
  branch = "master"

  [[constraint]]
  name =  "github.com/pquerna/otp"
  branch = "master"

  [[constraint]]
  name =  "github.com/go-errors/errors"
  branch = "master"